const pkg = (data) => ({
  cocok: [], baseline: [], optional: [], excluded: [], adjustment: [], customTrigger: [], examples: [], guardrail: '', ...data,
});

window.SOLIVATE_CATALOGUE = [
  pkg({
    id: 'personal-starter', group: 'personal', subcategory: 'Personal', name: 'Personal Starter', price: 'Rp299.000',
    audience: 'Mahasiswa, freelancer pemula, CV online, portfolio sederhana, personal landing page, dan profil profesional sederhana.',
    cocok: ['Mahasiswa', 'Freelancer pemula', 'CV online', 'Portfolio sederhana', 'Personal landing page', 'Profil profesional sederhana'],
    outcome: 'Presence profesional dalam satu halaman yang fokus pada profil, kredibilitas, portfolio, dan contact.',
    baseline: ['1 landing page', 'Sekitar 5–6 section', 'Profile / About', 'Skills / Services', 'Portfolio / Projects', 'Experience / Achievement', 'Testimonial bila diperlukan', 'Contact', 'WhatsApp / social CTA', 'Responsive desktop & mobile', 'Basic SEO', 'Hosting + SSL', 'Subdomain Solivate sesuai kebijakan'],
    excluded: ['CMS', 'Admin dashboard', 'Blog system', 'Database', 'Login / authentication', 'Custom application feature'],
    difference: 'Satu halaman fokus untuk hadir online. Belum ada CMS, dashboard, atau database.',
    useCase: 'Portfolio mahasiswa atau freelancer dengan CTA WhatsApp.',
    guardrail: 'Domain umum hanya dapat di-include jika final project di atas Rp400.000.',
  }),
  pkg({
    id: 'personal-professional', group: 'personal', subcategory: 'Personal', name: 'Personal Professional', price: 'Rp499.000+',
    audience: 'Freelancer profesional, consultant, creator, personal brand aktif, dan profesional dengan portfolio lebih besar.',
    cocok: ['Freelancer profesional', 'Consultant', 'Creator', 'Personal brand aktif', 'Profesional dengan portfolio lebih besar'],
    outcome: 'Personal branding yang lebih lengkap, kredibel, dan mudah dikembangkan.',
    baseline: ['Multipage website', 'Home', 'About', 'Portfolio / Projects', 'Experience / Achievement', 'Services bila diperlukan', 'Contact', 'Basic analytics', 'Search Console', 'SEO foundation', 'Custom domain umum sesuai kebijakan', 'Hosting + SSL'],
    optional: ['CMS — jika diaktifkan, final quotation Personal Website wajib di atas Rp500.000', 'Blog', 'Article management', 'Gallery management', 'Project management', 'Advanced animation', 'Additional pages', 'Multilingual'],
    difference: 'Naik dari landing page menjadi website multipage. CMS dan blog tetap add-on sesuai scope.',
    useCase: 'Website konsultan dengan halaman layanan, proyek, pengalaman, dan kontak.',
    guardrail: 'Personal Website + CMS wajib memiliki final quotation di atas Rp500.000.',
  }),
  pkg({
    id: 'wedding-invitation', group: 'personal', subcategory: 'Wedding', name: 'Wedding Invitation', price: 'Rp199.000+',
    audience: 'Wedding invitation, engagement, akad/walimah, dan private event invitation.',
    cocok: ['Wedding invitation', 'Engagement', 'Akad / walimah', 'Private event invitation'],
    outcome: 'Undangan digital yang elegan, mudah dibagikan, dan memuat seluruh informasi penting acara.',
    baseline: ['Couple profile', 'Detail acara', 'Countdown', 'Maps', 'Gallery', 'Background music', 'Gift information', 'Guest name personalization', 'RSVP sederhana', 'Share link', 'Responsive mobile'],
    optional: ['Video', 'Custom animation', 'Multiple event schedule', 'Custom illustration', 'Custom theme', 'Advanced RSVP', 'Additional gallery / media'],
    difference: 'Undangan lengkap untuk dibagikan, tetapi belum menjadi sistem database dan check-in tamu.',
    useCase: 'Undangan akad dan resepsi dengan nama tamu custom, RSVP sederhana, maps, dan gift.',
  }),
  pkg({
    id: 'wedding-guest-management', group: 'personal', subcategory: 'Wedding', name: 'Wedding Guest Management', price: 'Rp799.000+',
    audience: 'Wedding dengan database tamu, check-in digital, dan kontrol attendance.',
    cocok: ['Wedding dengan guest management', 'Acara dengan database tamu', 'Check-in digital', 'Reception dengan kontrol attendance'],
    outcome: 'Mengelola tamu mulai dari invitation, RSVP, hingga check-in venue dalam satu sistem.',
    baseline: ['Digital invitation', 'Guest database', 'RSVP management', 'Guest category', 'Unique guest identity', 'QR invitation / QR pass', 'Web-based QR scanner', 'Check-in status', 'Attendance dashboard', 'Search & filter', 'Basic export'],
    adjustment: ['Jumlah tamu', 'Jumlah scanner', 'Jumlah gate', 'Bulk import', 'Guest category', 'Pax management', 'Multiple venue', 'Multiple reception session'],
    difference: 'Bukan hanya undangan: sudah mencakup database, QR, scanner, dan dashboard attendance.',
    useCase: 'Resepsi dengan QR pass per tamu dan beberapa petugas check-in.',
    guardrail: 'Wedding full package / guest management wajib memiliki final quotation di atas Rp700.000.',
  }),
  pkg({
    id: 'institution-profile', group: 'personal', subcategory: 'Institution', name: 'Institution Profile', price: 'Rp499.000+',
    audience: 'Komunitas, yayasan, masjid, organisasi, lembaga pendidikan kecil, dan institusi non-government.',
    cocok: ['Komunitas', 'Yayasan', 'Masjid', 'Organisasi', 'Lembaga pendidikan kecil', 'Institusi non-government'],
    outcome: 'Digital presence yang kredibel untuk memperkenalkan organisasi, program, aktivitas, dan informasi penting.',
    baseline: ['Home', 'About / Profile', 'Organization', 'Program / Activities', 'Gallery', 'Contact', 'WhatsApp', 'Maps bila diperlukan', 'Basic SEO', 'Hosting + SSL'],
    difference: 'Website profil institusi tanpa kebutuhan pengelolaan konten rutin melalui dashboard.',
    useCase: 'Profil sekolah, komunitas, yayasan, atau masjid dengan program dan galeri.',
    guardrail: 'Domain umum hanya dapat di-include jika final project di atas Rp400.000.',
  }),
  pkg({
    id: 'institution-pro', group: 'personal', subcategory: 'Institution', name: 'Institution Pro', price: 'Rp799.000+',
    audience: 'Institusi yang rutin memperbarui informasi, program, berita, dokumen, agenda, atau aktivitas.',
    cocok: ['Institusi dengan berita rutin', 'Yayasan dengan program aktif', 'Masjid dengan agenda', 'Organisasi dengan dokumen publik'],
    outcome: 'Institusi dapat mengelola konten dan informasi secara mandiri tanpa selalu bergantung pada developer.',
    baseline: ['Semua fondasi Institution Profile', 'CMS', 'Admin dashboard', 'Program management', 'News / article', 'Agenda / event', 'Gallery', 'Documents', 'Announcement', 'Form', 'Search / filter sesuai kebutuhan'],
    customTrigger: ['Database peserta / siswa / jamaah', 'Payment', 'Attendance', 'Multiple staff', 'Workflow', 'Approval', 'Transaction', 'Multi-role', 'Mobile app'],
    difference: 'CMS dan dashboard membuat admin dapat mengelola berita, program, agenda, dokumen, serta galeri sendiri.',
    useCase: 'Portal masjid atau yayasan dengan berita, agenda, dokumen, galeri, dan CMS.',
    guardrail: 'Paket institusi yang menggunakan CMS wajib memiliki final quotation di atas Rp700.000.',
  }),

  pkg({
    id: 'umkm-starter', group: 'umkm', subcategory: 'UMKM Website', name: 'UMKM Starter', price: 'Rp499.000',
    audience: 'Warung, catering, laundry, bengkel, barbershop, jasa lokal, home industry, dan bisnis mikro.',
    cocok: ['Warung', 'Catering', 'Laundry', 'Bengkel', 'Barbershop', 'Jasa lokal', 'Home industry', 'Bisnis mikro'],
    outcome: 'Bisnis mudah ditemukan secara online dan calon customer diarahkan ke WhatsApp, contact, atau outlet.',
    baseline: ['1 landing page', 'Business profile', 'Product / service', 'Benefits', 'Gallery', 'Testimonial', 'Maps', 'WhatsApp CTA', 'Social media', 'Basic SEO', 'Hosting + SSL'],
    difference: 'Landing page penjualan sederhana tanpa CMS atau proses transaksi di dalam sistem.',
    useCase: 'Landing bisnis lokal dengan daftar layanan, galeri, lokasi, dan CTA WhatsApp.',
    guardrail: 'Domain umum hanya dapat di-include jika final project di atas Rp400.000.',
  }),
  pkg({
    id: 'umkm-professional', group: 'umkm', subcategory: 'UMKM Website', name: 'UMKM Professional', price: 'Rp1.099.000+',
    audience: 'UMKM berkembang, contractor, interior, agency kecil, F&B, service business, dan brand lokal.',
    cocok: ['UMKM berkembang', 'Contractor', 'Interior', 'Agency kecil', 'F&B', 'Service business', 'Brand lokal'],
    outcome: 'Website bisnis yang lebih profesional dan lengkap untuk meningkatkan trust dan presentasi brand.',
    baseline: ['Multipage website', 'Home', 'About', 'Product / Service', 'Portfolio / Gallery', 'Testimonial', 'Contact', 'Basic analytics', 'SEO foundation', 'Custom domain sesuai kebijakan', 'Hosting + SSL'],
    optional: ['CMS — final quotation UMKM dengan CMS wajib di atas Rp1.000.000', 'Product management', 'Blog', 'Promo', 'Gallery management', 'Lead form', 'Additional pages', 'WhatsApp automation'],
    difference: 'Naik dari landing menjadi multipage yang lebih kredibel. CMS tetap optional sesuai kebutuhan.',
    useCase: 'Travel, contractor, atau brand lokal dengan halaman layanan, portfolio, dan kontak.',
    guardrail: 'Company profile formal dan UMKM dengan CMS wajib memiliki final quotation di atas Rp1.000.000.',
  }),
  pkg({
    id: 'event-website', group: 'umkm', subcategory: 'Event', name: 'Event Website', price: 'Rp749.000+',
    audience: 'Seminar, workshop, kajian, conference kecil-menengah, community event, expo, festival, dan campaign event.',
    cocok: ['Seminar', 'Workshop', 'Kajian', 'Conference kecil–menengah', 'Community event', 'Expo', 'Festival', 'Campaign event'],
    outcome: 'Pusat informasi dan promosi event yang memudahkan calon peserta memahami acara dan melakukan action.',
    baseline: ['Hero', 'Countdown', 'Event overview', 'Agenda', 'Speaker', 'Venue', 'Sponsor / partner', 'FAQ', 'CTA', 'Responsive', 'Basic SEO', 'Social sharing'],
    optional: ['CMS — final quotation Event dengan CMS wajib di atas Rp700.000', 'Announcement', 'Gallery', 'Sponsor management', 'Speaker management', 'Agenda management'],
    difference: 'Fokus pada promosi dan informasi event; registrasi dapat memakai link eksternal.',
    useCase: 'Website seminar dengan agenda, pembicara, venue, sponsor, dan tombol daftar.',
    guardrail: 'Event dengan CMS wajib memiliki final quotation di atas Rp700.000.',
  }),
  pkg({
    id: 'event-registration', group: 'umkm', subcategory: 'Event', name: 'Event Registration', price: 'Rp1.499.000+',
    audience: 'Event gratis, undangan, seminar, workshop, gathering, atau expo yang membutuhkan registrasi dan database participant.',
    cocok: ['Event gratis', 'Undangan', 'Seminar', 'Workshop', 'Gathering', 'Expo dengan registrasi'],
    outcome: 'Mengelola registrasi peserta secara digital dan menyimpan seluruh data participant dalam dashboard.',
    baseline: ['Semua fondasi Event Website sesuai scope', 'Custom registration form', 'Participant database', 'Confirmation', 'Admin dashboard', 'Search', 'Filter', 'Export', 'Basic email notification'],
    optional: ['QR participant', 'Scanner', 'Attendance', 'WhatsApp notification', 'Custom form logic', 'Certificate generation', 'Multi-day registration'],
    difference: 'Mulai menyimpan participant ke database dan menyediakan dashboard admin.',
    useCase: 'Workshop dengan form custom, database peserta, konfirmasi email, filter, dan ekspor.',
  }),
  pkg({
    id: 'event-ticketing', group: 'umkm', subcategory: 'Event', name: 'Event Ticketing', price: 'Rp3.499.000+',
    audience: 'Conference, expo, paid seminar, festival, large community event, dan event berbayar dengan ticketing.',
    cocok: ['Conference', 'Expo', 'Paid seminar', 'Festival', 'Large community event', 'Event berbayar'],
    outcome: 'Mengelola penjualan tiket, pembayaran, ticket issuance, participant, dan check-in melalui satu sistem.',
    baseline: ['Event website', 'Ticket type', 'Ticket price', 'Quota', 'Checkout', 'Buyer data', 'Attendee data', 'Payment gateway integration', 'Payment tracking', 'Digital ticket', 'Unique QR', 'QR scanner', 'Attendance dashboard', 'Sales dashboard', 'Basic report'],
    adjustment: ['Expected visitors', 'Jumlah ticket', 'Peak traffic', 'Concurrent checkout', 'Jumlah gate dan scanner', 'Payment volume', 'Jumlah admin dan tipe tiket', 'Voucher / promo complexity', 'Multi-day / multiple venue', 'Infrastructure, monitoring, backup, support, dan event-day SLA'],
    customTrigger: ['20.000+ participant / visitor', 'High concurrent traffic', 'Banyak gate & scanner', 'Mission-critical check-in', 'Advanced accreditation', 'External system integration', 'Complex ticketing rules', 'Dedicated infrastructure', 'Event-day support / SLA', 'Annual platform dengan workflow besar'],
    difference: 'Alur komersial lengkap: checkout, payment, tiket digital, QR check-in, sales, dan attendance.',
    useCase: 'Conference berbayar dengan beberapa tipe tiket, QRIS, QR pass, scanner, dan laporan.',
  }),
  pkg({
    id: 'ecommerce-starter', group: 'umkm', subcategory: 'E-Commerce', name: 'E-Commerce Starter', price: 'Rp1.499.000+',
    audience: 'UMKM yang ingin memiliki toko online sendiri dengan order management dan pembayaran manual / confirmation sederhana.',
    cocok: ['Toko online pertama', 'UMKM dengan pembayaran manual', 'Single merchant', 'Katalog produk dan order'],
    outcome: 'Menerima order langsung melalui website dengan katalog, cart, checkout, dan dashboard order.',
    baseline: ['Storefront', 'CMS', 'Product management', 'Category', 'Product detail', 'Cart', 'Checkout', 'Customer data', 'Order management', 'Admin dashboard', 'Manual payment / simple confirmation'],
    difference: 'Fondasi toko online dengan order dashboard; pembayaran masih manual atau konfirmasi sederhana.',
    useCase: 'Bakery atau apparel store dengan katalog, cart, checkout, dan order admin.',
  }),
  pkg({
    id: 'ecommerce-business', group: 'umkm', subcategory: 'E-Commerce', name: 'E-Commerce Business', price: 'Rp2.499.000+',
    audience: 'Bisnis yang ingin proses penjualan dan pembayaran QRIS lebih otomatis.',
    cocok: ['Toko dengan QRIS otomatis', 'Brand dengan order aktif', 'Admin yang perlu payment tracking'],
    outcome: 'Mengotomatisasi checkout dan pembayaran agar order lebih mudah diproses oleh admin.',
    baseline: ['Semua E-Commerce Starter', 'Payment gateway QRIS sesuai provider', 'Payment tracking', 'Webhook / callback', 'Invoice / receipt', 'Customer management basic', 'Notification basic'],
    difference: 'Menambahkan lifecycle pembayaran otomatis dari checkout hingga status paid dan invoice.',
    useCase: 'Frozen food store dengan QRIS, payment tracking, invoice, dan notifikasi order.',
    guardrail: 'E-Commerce dengan Payment Gateway QRIS wajib memiliki final quotation di atas Rp2.000.000.',
  }),
  pkg({
    id: 'ecommerce-pro', group: 'umkm', subcategory: 'E-Commerce', name: 'E-Commerce Pro', price: 'Rp5.499.000+',
    audience: 'Growing retail, brand, dan toko online yang membutuhkan operasional lebih lengkap dan/atau lebih dari satu metode payment gateway.',
    cocok: ['Growing retail', 'Brand dengan inventory', 'Toko dengan promo dan shipping', 'Operasi penjualan aktif'],
    outcome: 'Mengelola penjualan, inventory, customer, promotion, shipping, dan reporting dari satu dashboard.',
    baseline: ['Semua fondasi E-Commerce Business', 'Multi-payment gateway / metode pembayaran tambahan sesuai provider dan scope', 'Inventory', 'Voucher / promo', 'Customer management', 'Sales report', 'Shipping integration', 'Basic roles bila diperlukan', 'Operational dashboard'],
    customTrigger: ['Multi-warehouse kompleks', 'Multi-branch retail', 'Advanced inventory', 'ERP integration', 'Complex refund / return', 'Multi-vendor', 'Marketplace', 'High traffic', 'High transaction', 'Mobile app', 'Advanced BI / reporting'],
    difference: 'Naik dari payment automation menjadi operasi commerce dengan inventory, promo, shipping, dan report.',
    useCase: 'Retail online dengan stok, voucher, pelanggan, pengiriman, dashboard, dan laporan penjualan.',
    guardrail: 'E-Commerce dengan multi-payment gateway wajib memiliki final quotation di atas Rp5.000.000.',
  }),
  pkg({
    id: 'business-system', group: 'umkm', subcategory: 'Business System', name: 'Business System', price: 'Rp2.500.000+',
    audience: 'Bisnis dengan satu proses utama yang ingin didigitalisasi.',
    cocok: ['CRM sederhana', 'Booking system', 'POS sederhana', 'Order/laundry/rental management', 'Lead management', 'Service request', 'Inventory atau invoice sederhana'],
    outcome: 'Mengubah proses yang berjalan melalui Excel, WhatsApp, catatan manual, atau tools terpisah menjadi satu sistem terstruktur.',
    baseline: ['Database', 'Admin dashboard', 'Customer / entity management', 'Transaction / request', 'Status', 'Notes', 'Search', 'Filter', 'Basic report', 'Export basic'],
    examples: ['CRM: Lead → Qualification → Follow-up → Quotation → Won / Lost', 'Booking: Service → Schedule → Customer → Booking → Status', 'POS: Product → Cashier → Transaction → Receipt', 'Laundry: Customer → Order → Processing → Ready → Completed', 'Rental: Asset → Availability → Booking → Payment → Return'],
    difference: 'Satu proses bisnis utama menjadi database dan workflow terstruktur. Jenis sistem mengikuti use case.',
    useCase: 'Booking barbershop, POS sederhana, CRM dasar, laundry, rental, atau order management.',
  }),
  pkg({
    id: 'operational-system', group: 'umkm', subcategory: 'Business System', name: 'Operational System', price: 'Rp5.000.000+',
    audience: 'Growing business yang menjadikan software sebagai alat kerja internal sehari-hari.',
    cocok: ['Travel operations', 'Service company operations', 'Education administration', 'Clinic operations ringan', 'Distributor operations', 'Procurement sederhana', 'Field service', 'Membership atau donation management'],
    outcome: 'Menyatukan user, staff, customer, transaction, workflow, document, notification, dan reporting dalam satu sistem operasional.',
    baseline: ['Multiple users', 'Staff', 'Customer', 'Transaction', 'Basic roles', 'Workflow', 'Document', 'Notification', 'Dashboard', 'Reports', 'Audit activity basic', 'CMS bila diperlukan'],
    customTrigger: ['Banyak department', 'Banyak branch', 'Role matrix kompleks', 'Approval chain kompleks', 'Banyak modul', 'Finance workflow besar', 'Mobile app', 'Multiple external integration', 'High-scale transaction', 'Mission-critical operation'],
    difference: 'Dipakai banyak user sebagai alat kerja harian; cakupannya melampaui satu proses sederhana.',
    useCase: 'Operasional travel, administrasi pendidikan, procurement, distributor, atau service company.',
  }),

  pkg({
    id: 'corporate-website', group: 'enterprise', subcategory: 'Corporate', name: 'Corporate Website', price: 'Rp2.500.000+',
    audience: 'CV berkembang, PT, corporate, consulting company, group company, dan professional service company.',
    cocok: ['CV berkembang', 'PT', 'Corporate', 'Consulting company', 'Group company', 'Professional service company'],
    outcome: 'Digital presence perusahaan yang profesional, kredibel, dan mudah dikelola.',
    baseline: ['Corporate website', 'CMS', 'Company profile', 'Service / product', 'Portfolio / case study', 'Team', 'Testimonial', 'News / insight', 'Contact', 'Lead form basic', 'SEO foundation', 'Analytics', 'Hosting + SSL'],
    optional: ['Careers', 'ESG / sustainability', 'Investor information', 'Document center', 'Multilingual', 'Advanced SEO', 'Integration'],
    difference: 'Standar corporate sudah mencakup CMS, content architecture, SEO, analytics, dan lead form dasar.',
    useCase: 'Company profile logistik atau consulting dengan layanan, case study, team, news, dan CMS.',
    guardrail: 'Semua deliverable company profile bisnis formal wajib memiliki final quotation di atas Rp1.000.000.',
  }),
  pkg({
    id: 'corporate-business', group: 'enterprise', subcategory: 'Corporate', name: 'Corporate Business', price: 'Rp5.000.000+',
    audience: 'Perusahaan yang ingin website terhubung dengan aktivitas bisnis.',
    cocok: ['Corporate dengan lead aktif', 'Request dan quotation online', 'Document workflow', 'Customer status tracking'],
    outcome: 'Menghubungkan corporate website dengan proses lead, request, quotation, document, customer, dan status melalui dashboard.',
    baseline: ['Corporate CMS', 'Lead / request database', 'Customer data', 'Document upload / management', 'Quotation / request flow', 'Status tracking', 'Admin dashboard', 'Reporting basic'],
    customTrigger: ['Multi-department', 'Multi-branch', 'Complex approval', 'Client portal besar', 'Enterprise integration', 'SSO', 'Advanced security', 'High traffic', 'Internal system lintas divisi'],
    difference: 'Website mulai menjadi business function dengan database, dokumen, quotation, status, dan dashboard.',
    useCase: 'Portal inquiry perusahaan dari lead masuk hingga quotation, dokumen, dan status proses.',
  }),
  pkg({
    id: 'government-website', group: 'enterprise', subcategory: 'Government', name: 'Government Website', price: 'Rp5.499.000+',
    audience: 'Desa, instansi, lembaga pemerintah, unit pemerintah, dan public information portal.',
    cocok: ['Desa', 'Instansi', 'Lembaga pemerintah', 'Unit pemerintah', 'Public information portal'],
    outcome: 'Portal informasi publik yang terstruktur, kredibel, dan dapat dikelola admin.',
    baseline: ['Profile', 'Organization', 'News', 'Agenda', 'Announcement', 'Documents', 'Publication', 'Gallery', 'CMS', 'Admin dashboard', 'Basic accessibility', 'Basic SEO'],
    difference: 'Portal publik dengan CMS, dokumen, accessibility, dan requirement stakeholder sektor pemerintah.',
    useCase: 'Portal desa atau instansi dengan berita, agenda, pengumuman, dokumen, dan publikasi.',
    guardrail: 'Website Government / sektor publik wajib memiliki final quotation di atas Rp5.000.000.',
  }),
  pkg({
    id: 'digital-public-service', group: 'enterprise', subcategory: 'Government', name: 'Digital Public Service', price: 'Rp10.000.000+',
    audience: 'Instansi yang membutuhkan layanan digital untuk masyarakat.',
    cocok: ['Layanan pengajuan', 'Complaint', 'Public submission', 'Tracking permohonan', 'Workflow verifikasi staf'],
    outcome: 'Mengubah proses layanan, pengajuan, complaint, atau submission menjadi workflow digital yang dapat diproses staff dan dipantau masyarakat.',
    baseline: ['Public submission', 'Custom form', 'Document upload', 'Reference number', 'Status tracking', 'Staff dashboard', 'Verification', 'Approval workflow', 'Notification', 'Report', 'Export'],
    customTrigger: ['Multi-unit', 'Multi-agency', 'Advanced approval chain', 'Integrasi sistem pemerintah', 'SSO', 'Sensitive data', 'Security atau audit requirement tinggi', 'Dedicated infrastructure', 'SLA', 'Large public traffic'],
    difference: 'Aplikasi layanan publik dua sisi: masyarakat mengajukan dan melacak, staf memverifikasi serta menyetujui.',
    useCase: 'e-Layanan dengan upload dokumen, nomor referensi, tracking, verifikasi, approval, dan laporan.',
  }),
  pkg({
    id: 'custom-enterprise', group: 'enterprise', subcategory: 'Custom', name: 'Custom Software & Enterprise Solution', price: 'Custom Quotation',
    audience: 'Project besar, kompleks, unik, atau high-risk yang tidak aman menggunakan fixed baseline package.',
    cocok: ['ERP', 'SaaS', 'Marketplace / multi-vendor', 'Multi-tenant platform', 'Mobile application', 'Healthcare system', 'Multi-branch system', 'Government integrated system', 'Complex CRM / procurement', 'High-scale platform'],
    outcome: 'Software yang dirancang khusus mengikuti workflow, skala, role, integration, security, dan kebutuhan operasional client.',
    baseline: ['Objective', 'User', 'Role', 'Module', 'Workflow', 'Approval', 'Data', 'Transaction', 'Reports', 'Documents', 'Integration', 'Security', 'Infrastructure', 'Timeline', 'Support', 'SLA bila diperlukan'],
    customTrigger: ['Multi-module kompleks', 'Multi-role / department / branch', 'Mobile application', 'Banyak integrasi kritikal', 'Approval kompleks', 'High traffic / transaction', 'Mission-critical', 'SLA khusus', 'Security / audit tinggi', 'ERP, SaaS, Marketplace, multi-tenant', 'Requirement terlalu unik'],
    difference: 'Tidak memakai fixed scope. Discovery dan module breakdown wajib dilakukan sebelum quotation final.',
    useCase: 'ERP, SaaS, marketplace, sistem travel lengkap, hospital system, atau platform enterprise.',
  }),
];

window.SOLIVATE_GROUPS = [
  { id: 'personal', number: '01', title: 'Personal & Non-Profit', short: 'Personal', subtitle: 'Website personal, wedding, komunitas, yayasan, dan institusi non-government.', accent: '#1456d9' },
  { id: 'umkm', number: '02', title: 'UMKM & Growing Business', short: 'UMKM', subtitle: 'Website bisnis, event, commerce, dan sistem operasional untuk usaha bertumbuh.', accent: '#457500' },
  { id: 'enterprise', number: '03', title: 'Business & Enterprise', short: 'Enterprise', subtitle: 'Corporate, public sector, dan software kompleks dengan discovery khusus.', accent: '#cc4b34' },
];
